version: '3.4'

services:
    dev:
        build: .
        image: ubuntu:node-exercise
        container_name: ubuntu-node-exercise
        ports:
            - 3000:3000
        volumes:
            - ../.nvmrc:/root/code/.nvmrc
            - ../package.json:/root/code/package.json
            - ../package-lock.json:/root/code/package-lock.json
            - ../.prettierrc:/root/code/.prettierrc
            - ../config.json:/root/code/config.json
            - ../jest.js:/root/code/jest.js
            - ../app.js:/root/code/app.js
            - ../server.js:/root/code/server.js
            - ../db:/root/code/db
            - ../lib:/root/code/lib
            - ../routes:/root/code/routes
