DROP TABLE IF EXISTS users;
CREATE TABLE users (
    user_name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS petitions;
CREATE TABLE petitions (
    starter_name INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

